import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'ta' | 'te' | 'pa';

interface LanguageContextType {
  currentLanguage: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'healthcare.without.barriers': 'Healthcare Without Barriers',
    'ai.powered.triage': 'AI-powered medical triage, 24/7 access, zero wait times. For everyone who can\'t reach a doctor easily.',
    'try.virtual.doctor': 'Try Virtual Doctor',
    'watch.how.works': 'Watch How It Works',
    'quick.health.check': 'Quick Health Check',
    'health.modules': 'Health Modules',
    'api.connection.test': 'API Connection Test',
    'nearby.healthcare': 'Nearby Healthcare',
    'find.hospitals.clinics': 'Find hospitals, clinics & pharmacies',
    'search.filter': 'Search & Filter',
    'search.placeholder': 'Search hospitals, clinics, pharmacies...',
    'all': 'All',
    'hospital': 'Hospital',
    'clinic': 'Clinic',
    'doctor': 'Doctor',
    'pharmacy': 'Pharmacy',
    'location.required': 'Location Required',
    'location.found': 'Location Found',
    'click.enable.location': 'Click to enable location access',
    'enable': 'Enable',
    'getting': 'Getting...',
    'healthcare.providers': 'Healthcare Providers',
    'open': 'Open',
    'closed': 'Closed',
    'call': 'Call',
    'directions': 'Directions',
    'sleep.health.analyzer': 'Sleep Health Analyzer',
    'track.improve.sleep': 'Track and improve your sleep patterns',
    'sleep.tracker': 'Sleep Tracker',
    'bedtime': 'Bedtime',
    'wake.time': 'Wake Time',
    'sleep.quality': 'Sleep Quality (1-10)',
    'sleep.interruptions': 'Sleep Interruptions',
    'analyze.sleep': 'Analyze Sleep',
    'analyzing': 'Analyzing...',
    'sleep.analysis': 'Sleep Analysis',
    'excellent': 'Excellent',
    'good': 'Good',
    'needs.improvement': 'Needs Improvement',
    'total.sleep': 'Total Sleep',
    'deep.sleep': 'Deep Sleep',
    'ai.recommendations': 'AI Recommendations:',
    'sleep.insights': 'Sleep Insights:',
    'content.loading': 'Content loading...',
    'health.dashboard': 'Health Dashboard',
    'all.systems.normal': 'All Systems Normal',
    'overview': 'Overview',
    'vitals': 'Vital Signs',
    'medications': 'Medications',
    'analytics': 'Analytics',
    'blood.pressure': 'Blood Pressure',
    'heart.rate': 'Heart Rate',
    'temperature': 'Temperature',
    'oxygen.saturation': 'Oxygen Saturation',
    'normal': 'Normal',
    'warning': 'Warning',
    'critical': 'Critical',
    'vital.signs.trend': 'Vital Signs Trend',
    'medication.compliance': 'Medication Compliance',
    'todays.progress': 'Today\'s Progress',
    'mark.taken': 'Mark Taken',
    'blood.pressure.history': 'Blood Pressure History',
    'latest.vital.signs': 'Latest Vital Signs',
    'medication.schedule': 'Medication Schedule',
    'taken': 'Taken',
    'mark.as.taken': 'Mark as Taken',
    'health.trends': 'Health Trends',
    'health.insights': 'Health Insights',
    'health.features': 'Health Features',
    'your.complete.health.overview': 'Your complete health overview',
    'ai.symptom.checker': 'AI Symptom Checker',
    'get.ai.powered.analysis': 'Get AI-powered analysis of your symptoms with triage recommendations',
    'mental.health.assistant': 'Mental Health Assistant',
    'talk.to.ai.therapist': 'Talk to our AI therapist for mental health support and CBT guidance',
    'diet.advisor': 'Diet Advisor',
    'personalized.nutrition.advice': 'Get personalized nutrition advice for Indian meals',
    'child.vaccine.tracker': 'Child Vaccine Tracker',
    'track.vaccination.schedules': 'Track vaccination schedules and growth milestones',
    'cognitive.health.screener': 'Cognitive Health Screener',
    'monitor.cognitive.function': 'Monitor cognitive function with brain games',
    'report.analysis': 'Report Analysis',
    'ai.powered.lab.analysis': 'AI-powered analysis of lab reports and medical documents',
    'available': 'Available'
  },
  hi: {
    'healthcare.without.barriers': 'बिना बाधाओं के स्वास्थ्य सेवा',
    'ai.powered.triage': 'एआई-संचालित चिकित्सा ट्राइएज, 24/7 पहुंच, शून्य प्रतीक्षा समय। उन सभी के लिए जो आसानी से डॉक्टर तक नहीं पहुंच सकते।',
    'try.virtual.doctor': 'वर्चुअल डॉक्टर आज़माएं',
    'watch.how.works': 'देखें यह कैसे काम करता है',
    'quick.health.check': 'त्वरित स्वास्थ्य जांच',
    'health.modules': 'स्वास्थ्य मॉड्यूल',
    'api.connection.test': 'एपीआई कनेक्शन टेस्ट',
    'nearby.healthcare': 'नजदीकी स्वास्थ्य सेवा',
    'find.hospitals.clinics': 'अस्पताल, क्लिनिक और फार्मेसी खोजें',
    'search.filter': 'खोजें और फ़िल्टर करें',
    'search.placeholder': 'अस्पताल, क्लिनिक, फार्मेसी खोजें...',
    'all': 'सभी',
    'hospital': 'अस्पताल',
    'clinic': 'क्लिनिक',
    'doctor': 'डॉक्टर',
    'pharmacy': 'फार्मेसी',
    'location.required': 'स्थान आवश्यक',
    'location.found': 'स्थान मिल गया',
    'click.enable.location': 'स्थान पहुंच सक्षम करने के लिए क्लिक करें',
    'enable': 'सक्षम करें',
    'getting': 'प्राप्त कर रहे हैं...',
    'healthcare.providers': 'स्वास्थ्य सेवा प्रदाता',
    'open': 'खुला',
    'closed': 'बंद',
    'call': 'कॉल करें',
    'directions': 'दिशा-निर्देश',
    'sleep.health.analyzer': 'नींद स्वास्थ्य विश्लेषक',
    'track.improve.sleep': 'अपने नींद के पैटर्न को ट्रैक और सुधारें',
    'sleep.tracker': 'नींद ट्रैकर',
    'bedtime': 'सोने का समय',
    'wake.time': 'जागने का समय',
    'sleep.quality': 'नींद की गुणवत्ता (1-10)',
    'sleep.interruptions': 'नींद में बाधा',
    'analyze.sleep': 'नींद का विश्लेषण करें',
    'analyzing': 'विश्लेषण कर रहे हैं...',
    'sleep.analysis': 'नींद का विश्लेषण',
    'excellent': 'उत्कृष्ट',
    'good': 'अच्छा',
    'needs.improvement': 'सुधार की आवश्यकता',
    'total.sleep': 'कुल नींद',
    'deep.sleep': 'गहरी नींद',
    'ai.recommendations': 'AI सुझाव:',
    'sleep.insights': 'नींद की जानकारी:',
    'content.loading': 'सामग्री लोड हो रही है...',
    'health.dashboard': 'स्वास्थ्य डैशबोर्ड',
    'all.systems.normal': 'सभी सिस्टम सामान्य',
    'overview': 'अवलोकन',
    'vitals': 'महत्वपूर्ण संकेत',
    'medications': 'दवाइयां',
    'analytics': 'विश्लेषण',
    'blood.pressure': 'रक्तचाप',
    'heart.rate': 'हृदय गति',
    'temperature': 'तापमान',
    'oxygen.saturation': 'ऑक्सीजन संतृप्ति',
    'normal': 'सामान्य',
    'warning': 'चेतावनी',
    'critical': 'गंभीर',
    'vital.signs.trend': 'महत्वपूर्ण संकेत प्रवृत्ति',
    'medication.compliance': 'दवा अनुपालन',
    'todays.progress': 'आज की प्रगति',
    'mark.taken': 'लिया गया चिह्नित करें',
    'blood.pressure.history': 'रक्तचाप इतिहास',
    'latest.vital.signs': 'नवीनतम महत्वपूर्ण संकेत',
    'medication.schedule': 'दवा अनुसूची',
    'taken': 'लिया गया',
    'mark.as.taken': 'लिया गया के रूप में चिह्नित करें',
    'health.trends': 'स्वास्थ्य रुझान',
    'health.insights': 'स्वास्थ्य अंतर्दृष्टि',
    'health.features': 'स्वास्थ्य सुविधाएं',
    'your.complete.health.overview': 'आपका संपूर्ण स्वास्थ्य अवलोकन',
    'ai.symptom.checker': 'AI लक्षण जांचक',
    'get.ai.powered.analysis': 'ट्राइएज सिफारिशों के साथ अपने लक्षणों का AI-संचालित विश्लेषण प्राप्त करें',
    'mental.health.assistant': 'मानसिक स्वास्थ्य सहायक',
    'talk.to.ai.therapist': 'मानसिक स्वास्थ्य सहायता और CBT मार्गदर्शन के लिए हमारे AI चिकित्सक से बात करें',
    'diet.advisor': 'आहार सलाहकार',
    'personalized.nutrition.advice': 'भारतीय भोजन के लिए व्यक्तिगत पोषण सलाह प्राप्त करें',
    'child.vaccine.tracker': 'बच्चे का टीकाकरण ट्रैकर',
    'track.vaccination.schedules': 'टीकाकरण कार्यक्रम और विकास मील के पत्थर को ट्रैक करें',
    'cognitive.health.screener': 'संज्ञानात्मक स्वास्थ्य स्क्रीनर',
    'monitor.cognitive.function': 'मस्तिष्क खेलों के साथ संज्ञानात्मक कार्य की निगरानी करें',
    'report.analysis': 'रिपोर्ट विश्लेषण',
    'ai.powered.lab.analysis': 'लैब रिपोर्ट और चिकित्सा दस्तावेजों का AI-संचालित विश्लेषण',
    'available': 'उपलब्ध'
  },
  ta: {
    'healthcare.without.barriers': 'தடைகள் இல்லாத சுகாதாரம்',
    'ai.powered.triage': 'AI-இயங்கும் மருத்துவ ட்ரையேஜ், 24/7 அணுகல், பூஜ்ய காத்திருப்பு நேரம். எளிதில் மருத்துவரை அணுக முடியாத அனைவருக்கும்.',
    'try.virtual.doctor': 'மெய்நிகர் மருத்துவரை முயற்சிக்கவும்',
    'watch.how.works': 'இது எப்படி வேலை செய்கிறது என்பதைப் பாருங்கள்',
    'quick.health.check': 'விரைவு சுகாதார சோதனை',
    'health.modules': 'சுகாதார தொகுதிகள்',
    'api.connection.test': 'API இணைப்பு சோதனை',
    'nearby.healthcare': 'அருகிலுள்ள சுகாதாரம்',
    'find.hospitals.clinics': 'மருத்துவமனைகள், கிளினிக்குகள் மற்றும் மருந்தகங்களைக் கண்டறியவும்',
    'search.filter': 'தேடல் மற்றும் வடிகட்டி',
    'search.placeholder': 'மருத்துவமனைகள், கிளினிக்குகள், மருந்தகங்களைத் தேடுங்கள்...',
    'all': 'அனைத்தும்',
    'hospital': 'மருத்துவமனை',
    'clinic': 'கிளினிக்',
    'doctor': 'மருத்துவர்',
    'pharmacy': 'மருந்தகம்',
    'location.required': 'இடம் தேவை',
    'location.found': 'இடம் கண்டுபிடிக்கப்பட்டது',
    'click.enable.location': 'இட அணுகலை இயக்க கிளிக் செய்யவும்',
    'enable': 'இயக்கு',
    'getting': 'பெறுகிறது...',
    'healthcare.providers': 'சுகாதார சேவை வழங்குநர்கள்',
    'open': 'திறந்தது',
    'closed': 'மூடப்பட்டது',
    'call': 'அழைக்கவும்',
    'directions': 'திசைகள்',
    'sleep.health.analyzer': 'தூக்க சுகாதார பகுப்பாய்வி',
    'track.improve.sleep': 'உங்கள் தூக்க முறைகளைக் கண்காணித்து மேம்படுத்தவும்',
    'sleep.tracker': 'தூக்க கண்காணிப்பு',
    'bedtime': 'படுக்கை நேரம்',
    'wake.time': 'எழுந்திரு நேரம்',
    'sleep.quality': 'தூக்க தரம் (1-10)',
    'sleep.interruptions': 'தூக்க இடையூறுகள்',
    'analyze.sleep': 'தூக்கத்தை பகுப்பாய்வு செய்யவும்',
    'analyzing': 'பகுப்பாய்வு செய்கிறது...',
    'sleep.analysis': 'தூக்க பகுப்பாய்வு',
    'excellent': 'சிறந்த',
    'good': 'நல்ல',
    'needs.improvement': 'மேம்பாடு தேவை',
    'total.sleep': 'மொத்த தூக்கம்',
    'deep.sleep': 'ஆழ்ந்த தூக்கம்',
    'ai.recommendations': 'AI பரிந்துரைகள்:',
    'sleep.insights': 'தூக்க நுண்ணறிவு:',
    'content.loading': 'உள்ளடக்கம் ஏற்றப்படுகிறது...',
    'health.dashboard': 'சுகாதார டாஷ்போர்டு',
    'all.systems.normal': 'அனைத்து அமைப்புகளும் சாதாரணம்',
    'overview': 'கண்ணோட்டம்',
    'vitals': 'முக்கிய அறிகுறிகள்',
    'medications': 'மருந்துகள்',
    'analytics': 'பகுப்பாய்வு',
    'blood.pressure': 'இரத்த அழுத்தம்',
    'heart.rate': 'இதய துடிப்பு',
    'temperature': 'வெப்பநிலை',
    'oxygen.saturation': 'ஆக்ஸிஜன் செறிவு',
    'normal': 'சாதாரணம்',
    'warning': 'எச்சரிக்கை',
    'critical': 'முக்கியமான',
    'vital.signs.trend': 'முக்கிய அறிகுறிகள் போக்கு',
    'medication.compliance': 'மருந்து இணக்கம்',
    'todays.progress': 'இன்றைய முன்னேற்றம்',
    'mark.taken': 'எடுத்ததாக குறிக்கவும்',
    'blood.pressure.history': 'இரத்த அழுத்த வரலாறு',
    'latest.vital.signs': 'சமீபத்திய முக்கிய அறிகுறிகள்',
    'medication.schedule': 'மருந்து அட்டவணை',
    'taken': 'எடுக்கப்பட்டது',
    'mark.as.taken': 'எடுத்ததாக குறிக்கவும்',
    'health.trends': 'சுகாதார போக்குகள்',
    'health.insights': 'சுகாதார நுண்ணறிவு'
  },
  te: {
    'healthcare.without.barriers': 'అడ్డంకులు లేని ఆరోగ్య సంరక్షణ',
    'ai.powered.triage': 'AI-శక్తితో కూడిన వైద్య ట్రయాజ్, 24/7 యాక్సెస్, జీరో వేట్ టైమ్స్. వైద్యుడిని సులభంగా చేరుకోలేని ప్రతి ఒక్కరికీ.',
    'try.virtual.doctor': 'వర్చువల్ డాక్టర్ని ప్రయత్నించండి',
    'watch.how.works': 'ఇది ఎలా పనిచేస్తుందో చూడండి',
    'quick.health.check': 'త్వరిత ఆరోగ్య తనిఖీ',
    'health.modules': 'ఆరోగ్య మాడ్యూల్స్',
    'api.connection.test': 'API కనెక్షన్ టెస్ట్',
    'nearby.healthcare': 'సమీపంలోని ఆరోగ్య సంరక్షణ',
    'find.hospitals.clinics': 'ఆసుపత్రులు, క్లినిక్లు మరియు ఫార్మసీలను కనుగొనండి',
    'search.filter': 'శోధన మరియు ఫిల్టర్',
    'search.placeholder': 'ఆసుపత్రులు, క్లినిక్లు, ఫార్మసీలను శోధించండి...',
    'all': 'అన్నీ',
    'hospital': 'ఆసుపత్రి',
    'clinic': 'క్లినిక్',
    'doctor': 'వైద్యుడు',
    'pharmacy': 'ఫార్మసీ',
    'location.required': 'స్థానం అవసరం',
    'location.found': 'స్థానం దొరికింది',
    'click.enable.location': 'స్థాన యాక్సెస్ను ప్రారంభించడానికి క్లిక్ చేయండి',
    'enable': 'ప్రారంభించు',
    'getting': 'పొందుతోంది...',
    'healthcare.providers': 'ఆరోగ్య సేవా ప్రదాతలు',
    'open': 'తెరిచింది',
    'closed': 'మూసివేయబడింది',
    'call': 'కాల్ చేయండి',
    'directions': 'దిశలు',
    'health.dashboard': 'ఆరోగ్య డాష్‌బోర్డ్',
    'all.systems.normal': 'అన్ని వ్యవస్థలు సాధారణం',
    'overview': 'అవలోకనం',
    'vitals': 'ముఖ్య సంకేతాలు',
    'medications': 'మందులు',
    'analytics': 'విశ్లేషణలు',
    'blood.pressure': 'రక్తపోటు',
    'heart.rate': 'హృదయ స్పందన',
    'temperature': 'ఉష్ణోగ్రత',
    'oxygen.saturation': 'ఆక్సిజన్ సంతృప్తత',
    'normal': 'సాధారణం',
    'warning': 'హెచ్చరిక',
    'critical': 'క్లిష్టమైన',
    'vital.signs.trend': 'ముఖ్య సంకేతాల ధోరణి',
    'medication.compliance': 'మందుల అనుసరణ',
    'todays.progress': 'నేటి పురోగతి',
    'mark.taken': 'తీసుకున్నట్లు గుర్తించండి',
    'blood.pressure.history': 'రక్తపోటు చరిత్ర',
    'latest.vital.signs': 'తాజా ముఖ్య సంకేతాలు',
    'medication.schedule': 'మందుల షెడ్యూల్',
    'taken': 'తీసుకున్నారు',
    'mark.as.taken': 'తీసుకున్నట్లు గుర్తించండి',
    'health.trends': 'ఆరోగ్య ధోరణులు',
    'health.insights': 'ఆరోగ్య అంతర్దృష్టులు'
  },
  pa: {
    'healthcare.without.barriers': 'ਬਿਨਾਂ ਰੁਕਾਵਟਾਂ ਦੇ ਸਿਹਤ ਸੇਵਾ',
    'ai.powered.triage': 'AI-ਸੰਚਾਲਿਤ ਮੈਡੀਕਲ ਟ੍ਰਾਈਏਜ, 24/7 ਪਹੁੰਚ, ਜ਼ੀਰੋ ਇੰਤਜ਼ਾਰ ਸਮਾਂ। ਉਹਨਾਂ ਸਾਰਿਆਂ ਲਈ ਜੋ ਆਸਾਨੀ ਨਾਲ ਡਾਕਟਰ ਤੱਕ ਨਹੀਂ ਪਹੁੰਚ ਸਕਦੇ।',
    'try.virtual.doctor': 'ਵਰਚੁਅਲ ਡਾਕਟਰ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'watch.how.works': 'ਦੇਖੋ ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    'quick.health.check': 'ਤੁਰੰਤ ਸਿਹਤ ਜਾਂਚ',
    'health.modules': 'ਸਿਹਤ ਮਾਡਿਊਲ',
    'api.connection.test': 'API ਕਨੈਕਸ਼ਨ ਟੈਸਟ',
    'nearby.healthcare': 'ਨੇੜਲੀ ਸਿਹਤ ਸੇਵਾ',
    'find.hospitals.clinics': 'ਹਸਪਤਾਲ, ਕਲੀਨਿਕ ਅਤੇ ਫਾਰਮੇਸੀ ਲੱਭੋ',
    'search.filter': 'ਖੋਜ ਅਤੇ ਫਿਲਟਰ',
    'search.placeholder': 'ਹਸਪਤਾਲ, ਕਲੀਨਿਕ, ਫਾਰਮੇਸੀ ਖੋਜੋ...',
    'all': 'ਸਾਰੇ',
    'hospital': 'ਹਸਪਤਾਲ',
    'clinic': 'ਕਲੀਨਿਕ',
    'doctor': 'ਡਾਕਟਰ',
    'pharmacy': 'ਫਾਰਮੇਸੀ',
    'location.required': 'ਸਥਾਨ ਲੋੜੀਂਦਾ',
    'location.found': 'ਸਥਾਨ ਮਿਲ ਗਿਆ',
    'click.enable.location': 'ਸਥਾਨ ਪਹੁੰਚ ਚਾਲੂ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    'enable': 'ਚਾਲੂ ਕਰੋ',
    'getting': 'ਪ੍ਰਾਪਤ ਕਰ ਰਿਹਾ ਹੈ...',
    'healthcare.providers': 'ਸਿਹਤ ਸੇਵਾ ਪ੍ਰਦਾਤਾ',
    'open': 'ਖੁੱਲ੍ਹਾ',
    'closed': 'ਬੰਦ',
    'call': 'ਕਾਲ ਕਰੋ',
    'directions': 'ਦਿਸ਼ਾਵਾਂ',
    'health.dashboard': 'ਸਿਹਤ ਡੈਸ਼ਬੋਰਡ',
    'all.systems.normal': 'ਸਾਰੇ ਸਿਸਟਮ ਸਾਧਾਰਨ',
    'overview': 'ਸੰਖੇਪ',
    'vitals': 'ਮਹੱਤਵਪੂਰਨ ਸੰਕੇਤ',
    'medications': 'ਦਵਾਈਆਂ',
    'analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'blood.pressure': 'ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ',
    'heart.rate': 'ਦਿਲ ਦੀ ਧੜਕਣ',
    'temperature': 'ਤਾਪਮਾਨ',
    'oxygen.saturation': 'ਆਕਸੀਜਨ ਸੰਤ੍ਰਿਪਤਤਾ',
    'normal': 'ਸਾਧਾਰਨ',
    'warning': 'ਚੇਤਾਵਨੀ',
    'critical': 'ਗੰਭੀਰ',
    'vital.signs.trend': 'ਮਹੱਤਵਪੂਰਨ ਸੰਕੇਤ ਰੁਝਾਨ',
    'medication.compliance': 'ਦਵਾਈ ਪਾਲਣਾ',
    'todays.progress': 'ਅੱਜ ਦੀ ਤਰੱਕੀ',
    'mark.taken': 'ਲਿਆ ਗਿਆ ਨਿਸ਼ਾਨ ਲਗਾਓ',
    'blood.pressure.history': 'ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ ਇਤਿਹਾਸ',
    'latest.vital.signs': 'ਨਵੀਨਤਮ ਮਹੱਤਵਪੂਰਨ ਸੰਕੇਤ',
    'medication.schedule': 'ਦਵਾਈ ਸਮਾਂ-ਸਾਰਣੀ',
    'taken': 'ਲਿਆ ਗਿਆ',
    'mark.as.taken': 'ਲਿਆ ਗਿਆ ਵਜੋਂ ਨਿਸ਼ਾਨ ਲਗਾਓ',
    'health.trends': 'ਸਿਹਤ ਰੁਝਾਨ',
    'health.insights': 'ਸਿਹਤ ਸੂਝ'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<SupportedLanguage>('en');

  useEffect(() => {
    const saved = localStorage.getItem('vaidyana-language') as SupportedLanguage;
    if (saved && translations[saved]) {
      setCurrentLanguage(saved);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setCurrentLanguage(lang);
    localStorage.setItem('vaidyana-language', lang);
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}